paths:
  dataset_json: data/hotpot_train_v1.1.json

data:
  sample: 20                 # 本地先小样本
  cache_dir: .cache/prep

model:
  name: sshleifer/tiny-gpt2  # 本地快跑先用 tiny 模型
  device: cpu                # 若 mps 可用再切回 mps
  max_new_tokens: 16         # 少生点 token，快

train:
  total_timesteps: 1000      # 先跑 200 步看日志

ppo:
  n_steps: 16                # ✅ 每 16 个 episode 就更新一次
  batch_size: 16
  gamma: 0.95
  learning_rate: 3e-4


baseline:
  mode: fixed            # fixed | random | none
  episodes: 50
  fixed:
    top_k: 20
    temperature: 0.7
    rerank_on: 0
eval:
  freq: 50        # 每隔多少 timesteps 评估一次
  episodes: 50    # 每次评估跑多少个 episode