paths:
  dataset_json: data/hotpot_train_v1.1.json

data:
  sample: 20                 # 本地先小样本
  cache_dir: .cache/prep

model:
  name: google/flan-t5-small
  device: mps         # 没有 MPS 就先 cpu
  max_new_tokens: 32

data:
  sample: 200
train:
  total_timesteps: 5000

ppo:
  n_steps: 32
  batch_size: 32
  gamma: 0.95
  learning_rate: 3e-4

baseline:
  mode: fixed
  episodes: 100
  fixed:
    top_k: 20
    temperature: 0.7
    rerank_on: 0

eval:
  freq: 200
  episodes: 100